-- Table CLIENTE
CREATE TABLE CLIENTE 
(
    IDCLI NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMCLI varchar2(20),
    APEPCLI varchar2(40),
    APEMCLI varchar2(40),
    DNICLI char(8),
    TELCLI char(9),
    GMLCLI varchar2(30),
    ESTCLI char(1) DEFAULT 'A' ,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
) ;

-- INSERT INTO CLIENTE
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Joel', 'Mamani','Quispe','77436585','963214587','Joel@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Jose', 'Torres','Sanches','22455689','987456123','Jose@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Paul' , 'Quispe','Meneses','78965321','951236478','Paul@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('jose' ,'Asuncion','Comas','74852396','985632147','Jose@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Cecilia' ,'Caceres','Lornejo','75214596','963214785','Cecilia@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Esteban' ,'Rigoberto','Alta','76325894','987563214','Esteban@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Macarena' ,'Bautista','Paucar','75315982','987451263','Macarena@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Jeremias' ,'Pantano','Aguila','25413698','978456123','Jeremias@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Aria' ,'Hurtado','Huerta','23456987','951427863','Aria@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Luz','Olivares','Carrera','15591061','951159863','olivares@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Alejandra','Mallqui','Barreto','15600378','952589863','mallqui@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Blanca','Coca','Naturalich','15600983','952753863','coca@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Sonia','Obispo','Gavino','15601549','952745863','obispo@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Katy','Ly','Albujar','15672355','952742583','ly@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Cele','Aleman','Cruz','15723366','952325863','aleman@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Carlos','Gabino','Dias','15726079','952736563','gabino@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Eva','Trujillo','Alejo','15757378','952745965','trujillo@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Silas','Leon','Espinoza','15942236','954125863','leon@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Deysi','Salazar','Garcia','16416033','958545863','salazar@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Pedro' ,'Castle','Gutierres','73156489','932145687','Pedro@gmail.com');
COMMIT;

select * from CLIENTE;

-- Table: COMPRA
CREATE TABLE COMPRA (
    IDCOM NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    IDPRO int  NOT NULL,
    FECCOM date  NOT NULL,
    TIPPAGCOM varchar2(30)  NOT NULL,
    PRETOTCOM number(8,2)  NOT NULL,
    ESTCOM char(1) DEFAULT 'A',
    CONSTRAINT COMPRA_pk PRIMARY KEY (IDCOM)
) ;

-- Table: COMPRA_DETALLE
CREATE TABLE COMPRA_DETALLE (
    IDCOMDET NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    IDMED int  NOT NULL,
    IDCOM int  NOT NULL,
    CANCOMDET integer  NOT NULL,
    SUBTOTCOMDET number(8,2)  NOT NULL,
    CONSTRAINT COMPRA_DETALLE_pk PRIMARY KEY (IDCOMDET)
) ;

-- Table: EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMP NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMEMP varchar2(40)  NOT NULL,
    APEPEMP varchar2(70)  NOT NULL,
    APEMEMP varchar2(70)  NOT NULL,
    DNIEMP char(8)  NOT NULL,
    USUEMP varchar2(20)  NOT NULL,
    PASEMP varchar2(16)  NOT NULL,
    TELEMP char(9)  NOT NULL,
    ESTEMP char(1) DEFAULT 'A',
    CONSTRAINT EMPLEADO_pk PRIMARY KEY (IDEMP)
) ;

-- INSERT INTO EMPLEADO
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Alma','Asto', 'Atoche','74521365','AlmaAsto','74521365','974687432');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jett','Robles', 'Zambrano','71456585','JettRobles','71456585','975738742');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ben','Yucra', 'Casas','76459325','Benyucra','76459325','954783867');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Juan','Oliva','Gustamante','74521222','oliva','74521222','954784447');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Pablo','Vasques', 'Rios','74521332','vasques','74521332','954782247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Luis',' Feijoo','Lama','75521332','feijoo','75528832','953332247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jaime','silva','Marchan','75444332','silva','75444332','953332247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ricardo','calmet','Rodriguez','00370639','calmet','00370639','953123247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Manuel','laque','Contreras','00421804','laque','00421804','952343247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Santos','leon','Franco','00426463','leon','00426463','952312347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Martin','Chumbe','Ruiz','00821661','chumbe','00821661','952147347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Loyta','Lopez','Peña','01004062','lopez','01004062','912347347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Julio','Linarez','Melendez','01221713','linarez','01221713','912236347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Juan','Bernedo','Soto','01230718','bernedo','01230718','914566347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ruben','Puma','Lopez','01285100','puma','01285100','917896347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Adrian','Sanizo','mamani','01307186','sanizo','01307186','917369347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jose','Choque','palli','01309966','choque','01309966','917369852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Rus','Foraquita','zapana','01315112','foraquita','01315112','917741852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Elena','Calderon','muños','01323690','calderon','01323690','914561852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Consuelo','Jimenes','Ladrillo','23126545','ConsueloJimenes','23126545','973654236');
COMMIT;

select * from EMPLEADO;

-- Table: MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    IDMED NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TIPOMED char(1)  NOT NULL,
    NOMMED varchar2(30)  NOT NULL,
    STOMED int  NOT NULL,
    LABMED varchar2(30)  NOT NULL,
    NUMLOTMED varchar2(7)  NOT NULL,
    PREMED DECIMAL(8,2)  NOT NULL,
    FECVENCMED date  NOT NULL,
    CONSTRAINT MEDICAMENTO_pk PRIMARY KEY (IDMED)
) ;

-- INSERT INTO MEDICAMENTO
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Amoxicilina',300,'74521365','2001651','5','15/March/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Clamoxyl',300,'74521365','2001651','5','15/March/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Diclofenaco',250,'71456585','2145785','5','20/March/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Dolotren',250,'71456585','2145785','5','20/March/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Espidifen',170,'76459325','3705356','2','12/March/22');
COMMIT;

select * from MEDICAMENTO;

-- Table: PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPRO NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    RAZSOCPRO varchar2(100)  NOT NULL,
    RAZCOMPRO varchar2(100)  NOT NULL,
    RUCPROV char(11)  NOT NULL,
    EMAPRO varchar2(100)  NOT NULL,
    CELPRO char(9)  NOT NULL,
    DIRPROV varchar2(100)  NOT NULL,
    ESTPROV char(1) DEFAULT 'A',
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (IDPRO)
) ;

-- Table: VENTA
CREATE TABLE VENTA (
    IDVEN NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FACVEN varchar2(8)  NOT NULL,
    FECVEN date  NOT NULL,
    IDEMP int  NOT NULL,
    IDCLI int  NOT NULL,
    ESTVEN char(1) DEFAULT 'A',
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
) ;

-- INSERT INTO VENTA
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010001','22/August/22','1','1');
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010002','22/August/22','2','2');
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010003','22/August/22','1','3');
select * from VENTA;

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENDET NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CANMED int  NOT NULL,
    ESTVEND char(1) DEFAULT 'A',
    IDMED int  NOT NULL,
    IDVEN int  NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
);
-- INSERT INTO VENTA_DETALLE
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('3','1','1');
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('2','2','2');
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('4','1','3');
COMMIT;

select * from VENTA_DETALLE;


-- foreign keys
-- Reference: COMPRA_DETALLE_COMPRA (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_COMPRA
    FOREIGN KEY (IDCOM)
    REFERENCES COMPRA (IDCOM);

-- Reference: COMPRA_DETALLE_MEDICAMENTO (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_MEDICAMENTO
    FOREIGN KEY (IDMED)
    REFERENCES MEDICAMENTO (IDMED);

-- Reference: COMPRA_PROVEEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (IDPRO)
    REFERENCES PROVEEDOR (IDPRO);

-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

-- Reference: VENTA_DETALLE_MEDICAMENTO (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_MEDICAMENTO
    FOREIGN KEY (IDMED)
    REFERENCES MEDICAMENTO (IDMED);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

-- Reference: VENTA_EMPLEADO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_EMPLEADO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);

-- VISTA.

CREATE VIEW VENTA_UNIDA AS
SELECT VENTA.IDVEN,VENTA.FACVEN,VENTA.FECVEN,VENTA.IDEMP,VENTA.IDCLI,
VENTA_DETALLE.IDVENDET,VENTA_DETALLE.CANMED,VENTA_DETALLE.IDMED,
UPPER (APEPEMP)|| ' ' || (APEMEMP) || ', ' || NOMEMP AS EMPLEADO,
UPPER (APEPCLI)|| ' ' || (APEMCLI) || ', ' || NOMCLI AS CLIENTE,
MEDICAMENTO.NOMMED AS MEDICAMENTO
FROM VENTA
JOIN VENTA_DETALLE ON VENTA_DETALLE.IDVEN = VENTA.IDVEN
JOIN EMPLEADO ON EMPLEADO.IDEMP=VENTA.IDEMP
JOIN CLIENTE ON CLIENTE.IDCLI=VENTA.IDCLI
JOIN MEDICAMENTO ON MEDICAMENTO.IDMED =VENTA_DETALLE.IDMED;

select * from VENTA_UNIDA;
select * from VENTA_DETALLE;
select * from VENTA;
select * from EMPLEADO;
select * from MEDICAMENTO;
select * from CLIENTE;

----Single Row Functions Part II --Conversion to Character Data
SELECT TO_CHAR(FECVENCMED, 'DD/MM/YYYY') AS formatted_date
FROM MEDICAMENTO;

-------utilizando diferentes modelos de formato Date 
SELECT TO_CHAR(FECVENCMED, 'Month dd, YYYY') AS formatted_date
FROM MEDICAMENTO;
    
SELECT TO_CHAR(FECVENCMED, 'fmMonth dd, YYYY') AS formatted_date
FROM MEDICAMENTO;
    
SELECT TO_CHAR(FECVENCMED, 'fmMonth ddth, YYYY') AS formatted_date
FROM MEDICAMENTO;
-----
SELECT TO_CHAR(FECVENCMED, 'fmDay ddth Mon, YYYY')
FROM MEDICAMENTO;

SELECT TO_CHAR(FECVENCMED, 'fmDay ddthsp Mon, YYYY')
FROM MEDICAMENTO;
    
SELECT TO_CHAR(FECVENCMED, 'fmDay, ddthsp "of" Month, Year')
FROM MEDICAMENTO;

----------------modelos de formato para tiempo
SELECT TO_CHAR(FECVENCMED, 'hh:mm')
FROM MEDICAMENTO;

SELECT TO_CHAR(FECVENCMED, 'hh:mm pm')
FROM MEDICAMENTO;

SELECT TO_CHAR(FECVENCMED, 'hh:mm:ss pm')
FROM MEDICAMENTO;

-----------------números a datos de caracteres
SELECT TO_CHAR(3000, '$99999.99')
FROM MEDICAMENTO;

SELECT TO_CHAR(4500, '99,999')
FROM MEDICAMENTO;
    
SELECT TO_CHAR(9000, '99,999.99')
FROM MEDICAMENTO;
    
SELECT TO_CHAR(4422, '0009999')
FROM MEDICAMENTO;

----------------Reglas del modificador fx
SELECT TO_DATE('Sep 07, 1965','fxMon dd, YYYY') AS "Date"
FROM MEDICAMENTO;
    
SELECT TO_DATE('July312004','fxMonthDDYYYY') AS "Date"
FROM MEDICAMENTO;

SELECT TO_DATE('June 19, 1990','fxMonth dd, YYYY') AS "Date"
FROM MEDICAMENTO;

------------------RR Date Format and YY Date Format
SELECT TO_DATE ('27-Oct-95', 'DD-Mon-YY')AS "Date"
FROM dual; 

SELECT TO_DATE ('27-Oct-95', 'DD-Mon-RR')AS "Date"
FROM dual; 

------------------How Functions are Evaluated
SELECT TO_CHAR(NEXT_DAY(ADD_MONTHS(FECVENCMED, 6), 'FRIDAY'), 
'fmDay, Month ddth, YYYY') AS "Next Evaluation"
FROM MEDICAMENTO
WHERE IDMED = 5;

------------------Joins Part I
SELECT v.FACVEN, v.FECVEN, 
c.NOMCLI, c.APEPCLI, c.APEMCLI
FROM VENTA v
JOIN CLIENTE c ON v.IDCLI = c.IDCLI;

SELECT FACVEN, APEPCLI, APEMCLI, NOMCLI, APEPEMP, APEMEMP
FROM VENTA
JOIN CLIENTE USING (IDCLI)
JOIN EMPLEADO USING (IDEMP);

--------Inner versus Outer Joins
SELECT e.FACVEN, e.FECVEN, d.NOMCLI
FROM VENTA e
RIGHT OUTER JOIN CLIENTE d
ON (e.IDCLI = d.IDCLI);

SELECT e.FACVEN, e.FECVEN AS "FECHA", jh.NOMCLI AS "NOMBRE", 
jh.APEPCLI
FROM VENTA e
FULL OUTER JOIN CLIENTE jh ON (e.IDCLI = jh.IDCLI);

SELECT e.FACVEN, e.FECVEN AS "FECHA", jh.NOMCLI AS "NOMBRE", 
jh.APEPCLI
FROM VENTA e
LEFT OUTER JOIN CLIENTE jh ON (e.IDCLI = jh.IDCLI);

---------------Oracle Equijoin and Cartesian Products
SELECT VENTA.IDVEN, CLIENTE.IDCLI
FROM VENTA, CLIENTE
WHERE VENTA.IDVEN = CLIENTE.IDCLI;

SELECT e.FACVEN, d.NOMCLI, l.NOMEMP
FROM VENTA e, CLIENTE d, EMPLEADO l
WHERE e.IDCLI = d.IDCLI
AND d.IDCLI = l.IDEMP

-----------Oracle Nonequijoins and Outer Joins
SELECT e.FACVEN,
       d.IDCLI,
       d.NOMCLI
FROM VENTA e
LEFT JOIN CLIENTE d ON e.IDCLI = d.IDCLI(+);